# Generated by Django 3.2.8 on 2021-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=60, verbose_name='О нас')),
                ('title2', models.CharField(max_length=60, verbose_name='Что делаем')),
                ('text', models.TextField(verbose_name='Описание')),
                ('service1', models.CharField(max_length=60, verbose_name='Услуга1')),
                ('service2', models.CharField(max_length=60, verbose_name='Услуга2')),
                ('service3', models.CharField(max_length=60, verbose_name='Услуга3')),
                ('service4', models.CharField(max_length=60, verbose_name='Услуга4')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
