# Generated by Django 3.2.8 on 2021-10-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allmodels', '0003_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
