# Generated by Django 3.2.8 on 2021-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmodels', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выбор',
            },
        ),
        migrations.CreateModel(
            name='Tictoc_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tictoc_link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тикток',
                'verbose_name_plural': 'Тикток',
            },
        ),
    ]
