# Generated by Django 3.2.8 on 2021-10-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmodels', '0007_delete_tictoc_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tictoc_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tictoc_link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тикток',
                'verbose_name_plural': 'Тикток',
            },
        ),
    ]
