# Generated by Django 3.2.8 on 2021-10-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allmodels', '0008_tictoc_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tictoc_carousel',
        ),
    ]
