# Generated by Django 3.2.8 on 2021-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmodels', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='subtitle',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
